import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./componentes/navbar/Navbar";
import { poppins } from "@/config/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='es'>
			<body className={` ${poppins.className} antialiased`}>
				<Navbar />
				<div className='mt-32'>{children}</div>
			</body>
		</html>
	);
}
